# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
  favicon: "/img/icon.png"
  keywords: charmingsong blog
  backgroundpic: "img/bg.jpg"

Intro:
  name: charmingsong blog
  slogan: "Cause morning rolls around and it's another day of sun."
  HeadButton: massively

Nav:
  Home_name: 主页
  is_use_categories: true
  categories_name: 分类
  is_use_archives: false
  archives_name: 归档

  #Social
  # for more icons, please see http://fontawesome.io/icons/#brand
  icon:
    github: https://github.com/web-songsong

  pages:
  #        简历: 
  #            link: "/about/"
  #        团队 :
  #            link: "/group/"
  #        图库 :
  #            link: "/gallery/"
          标签:
              link: "/tag/"
  #自定义标签名
  #   link：“路径”

MainFirst:
  name: charmingsong
  description: Let's hope tomorrow's better.
  pic_url: /images/me.jpg
  goto_ulr: "https://websong.xin"

#Gallery :
#    title:
#    description: 

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# default dark funky okaidia twilight coy solarized  可选项  
# link to review : http://prismjs.com/index.html   官网预览
prism: okaidia


# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
  use: false
#    shortname: 
#    duoshuo_thread_key_type: 
#    duoshuo_embed_js_url: 
#    changyan_appid:
#    changyan_conf:
#    changyan_thread_key_type: 
#    # 使用 valine 请先执行 npm install valine --save
#    valine: # Valine Comment System https://github.com/xCss/Valine
#       on: true
#       appId: 'your appId'
#       appKey: 'your appkey'
#       notify: true
#       verify: false
#       placeholder: Please leave your footprints
#       avatar: ''
#       avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
#       pageSize: 10 # comments of one page

# Search Systems
# Available value:
#     swiftype | google | local
search:
  use: google
  swiftype_key: Just another fine responsive


# Leancloud Views
leancloud:
  enable: false
  app_id: #你的 app_id
  app_key: #你的 app_key
  av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
  enable: false
  all_site_uv: false
  post_pv: false
#  busuanzi_pure_mini_js:


# Mathjax 支持库 
mathjax:
  enable: false
  per_page: false
#  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML